config/routes.rb
# Copyright 2011-2012 Rice University. Licensed under the Affero General Public 
# License version 3 or later.  See the COPYRIGHT file for details.

Ost::Application.routes.draw do

  resources :terp, only: [] do  # can hack the use of the ID to be the quiz ID
    get 'sign_in'
    get 'forgot_password'
    post 'forgot_password'
    post 'reset_password'
    delete 'logout'
    get 'logout' # helps some weird error happens when timed out of session and try delete logout
    get "sign_up"
    post "sign_up"
    post "register"
    get "solicit_email_confirmation"
    post "confirm_email"
    get 'resend_confirmation_email'
    
    get "consent"
    get "quiz_start"
    get "missing_assignment"
    get "missing_exercises"
    get "too_many_assignments"
    get "my_account"
    get "preview"
    get "ca"

    get 'solicit_free_response'
    put 'save_free_response'
    get 'solicit_answer_selection'
    put 'save_answer_selection'
    get 'present_feedback'

    get "quiz_summary"

    get "instructions"
    get "dashboard"
    get "dashboard_consent"
    get "help"
    get 'terms'
    get 'contact_us'
    get "about"
    get "tutorial"
    get "my_account"
    get "full_page_consent"

    post "change_password"
    # get "account_help"
  end

  get 'escaped_terp', to: 'terp#escaped_terp'
  get 'quick_close', to: 'home#quick_close'

  resources :mail_hooks, :only => [] do
    post 'catch', :on => :collection
  end

  resources :site_licenses  # deprecated

  resources :consent_forms
  resources :consent_options, :only => [:show, :edit, :update]
  
  # 
  # resources :organization_managers
  # resources :researchers
  # 

  get "admin", :to => 'admin#index'
  put "admin/cron", :to => 'admin#cron', :as => "cron"
  get "admin/clone_klass", to: 'admin#clone_klass'
  post "admin/clone_klass", to: "admin#clone_klass"
  get "admin/raise_security_transgression", :to => 'admin#raise_security_transgression'
  get "admin/raise_record_not_found",       :to => 'admin#raise_record_not_found'
  get "admin/raise_routing_error",          :to => 'admin#raise_routing_error'
  get "admin/raise_unknown_controller",     :to => 'admin#raise_unknown_controller'
  get "admin/raise_unknown_action",         :to => 'admin#raise_unknown_action'
  get "admin/raise_missing_template",       :to => 'admin#raise_missing_template'
  get "admin/raise_not_yet_implemented",    :to => 'admin#raise_not_yet_implemented'
  get "admin/raise_illegal_argument",       :to => 'admin#raise_illegal_argument'

  get "research", :to => 'research#index'

  get "catalog", :to => 'catalog#index'

  resources :organizations do
    resources :courses, :shallow => true
  end
  
  resources :courses, :only => [] do
    resources :course_instructors, :shallow => true, :only => [:new, :create, :destroy] do
      collection do
        post 'search'
      end
    end
    
    # resources :offered_courses, :shallow => true, :except => [:index]
    resources :classes, :as => 'klasses', :shallow => true, :except => [:index]
  end

  resources :classes, :as => 'klasses', :only => [:index] do
    resources :educators, :shallow => true, :only => [:new, :create, :destroy, :show, :edit, :update] do
      collection do
        post 'search_instructors' => 'educators#search', :type => 'instructor'
        post 'search_graders' => 'educators#search', :type => 'grader'
        post 'search_assistants' => 'educators#search', :type => 'teaching_assistant'
      end
    end
    resources :students, :shallow => true, :only => [:index, :show, :update, :edit]
    resources :sections, :shallow => true
    resources :external_assignments, :shallow => true, :except => [:new, :edit, :update] do
      post 'sort', :on => :collection
      get  'show_table',   :on => :member
      put  'update_table', :on => :member
      get  'report',       :on => :collection
      resources :external_assignment_exercises, :shallow => true, :only => [:create] do
        post 'sort', :on => :collection
      end
    end
    resources :registration_requests, :shallow => true, :only => [:new, :index]
    resources :learning_conditions, :shallow => true, :only => [:index]
    resources :cohorts, :shallow => true
    resources :analytics, :only => [:index]
    get 'preview_assignments', :on => :member
    get 'report', :on => :member
    get 'class_grades', :on => :member
    get 'management_overview', :on => :member
  end

  resources :assignment_exercises, :only => [:show]

  resources :external_assignments, :shallow => true, :only => [ ] do
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end

  resources :external_assignment_exercises, :shallow => true, :only => [:destroy] do
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end

  resources :student_external_assignments, :shallow => true, :only => [ ] do
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end

  resources :student_external_assignment_exercises, :shallow => true, :only => [ ] do
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end

  resources :learning_conditions, :only => [] do
    resources :schedulers, :shallow => true, :except => [:index, :show, :destroy]
    resources :learning_condition_presentation_conditions, :shallow => true, :except => [:index, :show] do
      post 'sort', :on => :collection
    end
    resources :learning_condition_feedback_conditions, :shallow => true, :except => [:index, :show] do
      post 'sort', :on => :collection
    end
  end

  resources :learning_condition_default_presentation_conditions, only: [ :edit, :update ]
  resources :learning_condition_default_feedback_conditions,     only: [ :edit, :update ]

  resources :percent_schedulers, :only => [] do
    post 'add_schedule'
    post 'add_schedule_row'
    delete 'pop_schedule_row'
  end
  
  resources :students, :only => [] do
    put 'drop', :on => :member
  end
  
  resources :registration_requests, :except => [:new, :index] do 
    put 'approve', :as => "approve", :on => :member
    put 'reject', :as => "reject", :on => :member
  end
      
  resources :learning_plans, :only => [:show, :edit, :update] do
    resources :topics, :shallow => true, :except => [:new, :index, :show]
    resources :assignment_plans, :shallow => true
    resources :concepts, :shallow => true do
      post 'sort', :on => :collection
    end
    put 'refresh_exercises'
  end
  
  resources :assignment_plans do
    resources :assignment_plan_topics, :shallow => true, :only => [:new, :create, :destroy, :update]
  end
  
  resources :assignments, :only => [:show] do
    get 'grades', :on => :member
  end
  
  resources :topics, :only => [] do
    resources :resources, :shallow => true, :except => [:index, :show] do
      post 'sort', :on => :collection
    end
    resources :topic_exercises, :shallow => true, :except => [:index, :show] do
      post 'sort', :on => :collection
    end
  end
    
  resources :response_times, :only => [:create]

  resources :student_assignments, :only => [:show] do
    resources :assignment_coworkers, :shallow => true, :only => [:new, :create, :destroy] do
      collection do
        post 'search'
      end
    end
  end
  
  resources :student, :only => [] do
    resources :student_assignments, :only => [:index]
    resources :consents, :shallow => true, :except => [:index, :show, :edit, :update, :destroy]
  end

  resources :student_exercises, :only => [:show, :update] do
    get 'feedback'
    put 'make_correct'
    get 'score_detail'
    resources :free_responses, :shallow => true, :except => [:index, :show] do
      post 'sort', :on => :collection
      get 'email_instructions', :on => :collection
      get 'refresh', :on => :collection
    end
  end

  resources :text_free_responses, :only => [] do
    get 'preview', :on => :collection
  end

  resources :file_free_responses, :only => [] do
    get 'view', :on => :member
  end

  
  # For users, we mix devise with our own users controller.  We have overriden
  # some devise controller methods, so point that out here.
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :confirmations => "confirmations"}

  resources :users, :only => [:index, :show, :edit, :update] do
    post 'become'
    put 'confirm'
  end

  post "write", :to => 'write#index', :as => 'write'

  mount FinePrint::Engine => "/fine_print"

  get 'terms', :to => 'home#terms'
  get 'contact', :to => 'home#contact'
  post 'contact', :to => 'home#contact_submit', :as => 'contact_submit'
  get 'join', :to => 'home#join'
  get 'dashboard', :to => 'home#dashboard'
  get 'about', :to => 'home#about'
  get 'mytutor', :to => 'home#mytutor'
  get 'help', :to => 'help#index'
  
  get 'help/blurbs/:blurb_name', :to => 'help#blurb', :as => 'blurb_help'
  match 'help/faq'
  match 'help/student_getting_started'
  match 'help/assignments'
  match 'help/topics'
  match 'help/scheduling'
  match 'help/instructor_getting_started'
  match 'help/learning_conditions'
  match 'help/class_settings'
  match 'help/student_tutorials'
  match 'help', :to => 'help#index'
  match 'help/instructor_faq'
  
  get "terms/:id/show", to: "terms#show", as: "show_terms"
  get "terms/pose", to: "terms#pose", as: "pose_terms"
  post "terms/agree", to: "terms#agree", as: "agree_to_terms"

  get 'dev/toolbox', :as => 'dev_toolbox'
  put 'dev/reset_time'
  post 'dev/freeze_time'
  post 'dev/time_travel'
  post 'dev/run_cron_tasks'
  match 'dev/test_error/:number', :to => 'dev#test_error'
  
  resources :website_configurations, :only => [:index] do
    collection do
      get 'edit'
      put 'update'
    end
  end
  

  match '/', :to => 'home#index', :as => ''
  root :to => "home#index"

end

app/controllers/classes_controller.rb
# Copyright 2011-2012 Rice University. Licensed under the Affero General Public 
# License version 3 or later.  See the COPYRIGHT file for details.


class ClassesController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:index]
  fine_print_skip_signatures :general_terms_of_use, :privacy_policy, only: [:index]
  before_filter :get_course, :only => [:new, :create]
  before_filter :set_time_zone, :only => [:create, :update]
  before_filter :enable_clock

  def index
    @klasses = Klass.current.where{end_date > Time.zone.now}.select{|kk| present_user.can_read?(kk)}
  end

  def show
    @klass = Klass.find(params[:id])
    raise SecurityTransgression unless present_user.can_read?(@klass)
    turn_on_consenting(@klass.student_for(present_user))
  end

  def new
    @klass = Klass.new
    @klass.course = @course

    redirect_to catalog_path, :alert => "A manager at #{@course.organization.name} needs to give you permission to teach this class." \
      unless present_user.can_create?(@klass)
  end

  def help; end

  def edit
    @klass = Klass.find(params[:id])
    raise SecurityTransgression unless present_user.can_update?(@klass)
  end

  def create
    @klass = Klass.new(params[:klass])
    @klass.course = @course
    @klass.creator = present_user
    raise SecurityTransgression unless present_user.can_create?(@klass)    

    respond_to do |format|
      if @klass.save
        format.html { redirect_to @klass, notice: 'Class was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @klass = Klass.find(params[:id])
    raise SecurityTransgression unless present_user.can_update?(@klass)
    @klass.enable_admin_controls = present_user.is_administrator?

    respond_to do |format|
      if @klass.update_attributes(params[:klass])
        format.html { redirect_to @klass, notice: 'Class was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @klass = Klass.find(params[:id])
    raise SecurityTransgression unless present_user.can_destroy?(@klass)
    @klass.destroy
    redirect_to klasses_url
  end
  
  def preview_assignments
    @klass = Klass.find(params[:id])
    raise SecurityTransgression unless present_user.can_read?(@klass.learning_plan)
    
    @assignments = []
    
    # We probably have to save assignments during this "preview" so do it
    # in a transaction so we can roll everything back.
    Klass.transaction do
    
      @cohorts = @klass.cohorts
      learning_conditions = @cohorts.collect{|c| c.learning_condition}
    
      # Iterate through learning plans, building up assignments
      @klass.learning_plan.assignment_plans.each do |assignment_plan|
        @assignments.push([])

        # Iterate through the cohorts, pushing the assignments for them onto the list
        @cohorts.each_with_index do |cohort, cc|
          
          next if !assignment_plan.applies_to_klass_cohort?(cohort)
          
          # If this assignment plan has already had an assignment built for it
          # (because it has already been sent out) use it; otherwise, make it
          
          assignment = cohort.assignments.where{assignment_plan_id == assignment_plan.id}.first
          
          if assignment.nil?
            learning_condition = learning_conditions[cc]
            assignment = learning_condition.build_assignment(assignment_plan)
            assignment.dry_run = true
            assignment.save
          end
          
          @assignments.last.push(assignment)
        end
      end   
    
      raise ActiveRecord::Rollback
    end   
       
  end
  
  def report
    @klass = Klass.for_report.find(params[:id])
        
    raise SecurityTransgression unless present_user.can_read_children?(@klass, :report)
    
    respond_to do |format|
      # format.csv
      format.xls { render 'report' }
    end
  end
  
  def class_grades
    @klass = Klass.includes(:learning_plan => {
                              :assignment_plans => {
                                :assignments => {
                                  :student_assignments => :student_exercises
                                }
                              }
                            }).find(params[:id])

    raise SecurityTransgression unless present_user.can_read_children?(@klass, :class_grades)

    respond_to do |format|
      format.xls
    end
  end

  def management_overview
    @klass = Klass.find(params[:id])

    raise SecurityTransgression unless present_user.can_read_children?(@klass, :management_overview)
  end

protected

  def get_course
    @course = Course.find(params[:course_id])
  end

  def set_time_zone
    Time.zone = params[:klass][:time_zone]
  end

end

app/helpers/class_helper.rb
# Copyright 2011-2012 Rice University. Licensed under the Affero General Public 
# License version 3 or later.  See the COPYRIGHT file for details.

module ClassHelper
  def report_coworkers(student_assignment, user=present_user)
    students = student_assignment.assignment_coworkers.collect{|acw| acw.student}.concat([student_assignment.student])
    student_names = students.collect do |student|
      if user.is_researcher?
        student.consented? ? student.full_name(user) : "non-consenting student"
      else
        student.full_name(user)
      end
    end
    student_names.sort_by{|name| name.downcase}.join(',')
  end
end

app/views/classes/_nonstudent_assignments.html.erb
<%# Copyright 2011-2012 Rice University. Licensed under the Affero General Public 
    License version 3 or later.  See the COPYRIGHT file for details. %>

<%= section "Educator Assignment Overview", {:classes => "issued_assignments", :collapsible => true, :collapsed => false} do %>

  <% student        = klass.student_for(present_user) %>
  <% student_cohort = student.try(:cohort) %>

  <% assignment_plans = klass.learning_plan.assignment_plans.select{|ap| ap.assigned?}.sort_by{|ap| ap.number} %>
    
  <% if assignment_plans.none? %>
    <p>No assignments yet!</p>
  <% else %>

    <table class="list assignment">
      <tr>
        <th class="assignment_number"></th>
        <th class="assignment_name">Name</th>
        <th class="assignment_start">Starts</th>
        <th class="assignment_end">Ends</th>
      </tr>

      <% assignment_plans.each do |plan| %>

        <tr>
          <td class="assignment_number"><%= 1+plan.number %>.</td>
          <td class="assignment_name"><%= plan.name %></td>
          <td class="assignment_start"><%= standard_date(plan.starts_at) %></td>
          <td class="assignment_end"><%= standard_date(plan.ends_at) %></td>
        </tr>

        <% assignments = plan.assignments.sort_by{|assignment| assignment.cohort.number} %>
        <% assignments.each do |assignment| %>
          <tr>
            <td></td>
            <td colspan="3">
              &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to assignment.cohort.name, assignment %><%= '  (me)' if assignment.cohort == student_cohort %>
            </td>
          </tr>
        <% end %>

      <% end %>

    </table>

  <% end %>

<% end %>

app/views/classes/_report_heading_cell.xls.erb
        <Cell>
          <Data ss:Type="String"><%= data %></Data>
          <Comment ss:Author="<%= SITE_NAME %>">
            <Data><Font html:Size="9" html:Color="#000000" xmlns="http://www.w3.org/TR/REC-html40"><%= comment %></Font></Data>
          </Comment>
        </Cell>

app/views/classes/edit.html.erb
<%# Copyright 2011-2012 Rice University. Licensed under the Affero General Public 
    License version 3 or later.  See the COPYRIGHT file for details. %>

<%= pageHeading "Editing a Class" %>

<%= render 'form' %>

<% navitem { link_to "Class", @klass } %>

app/views/classes/management_overview.html.erb
<% user_is_researcher = present_user.is_researcher? %>
<% user_is_visitor    = present_user.is_visitor? %>

<% registration_status_sort_order = [ student_status_string_short_registered,
                                      student_status_string_short_auditing,
                                      student_status_string_short_dropped ] %>

<%
  students = @klass.students.visible(present_user).sort_by do |student|
    [
      student.section.klass.sections.index(student.section),
      student.cohort.number,
      registration_status_sort_order.index(student_status_string_short(student)),
      (user_is_researcher || user_is_visitor) ? student.user.research_id : "#{student.user.last_name} #{student.user.first_name}".downcase
    ]
  end
%>

<%= pageHeading "Class Management Overview: #{@klass.course.name}" %>

<div>

  <table class="list klass_management_overview" width="100%">
  <tr>
    <th width="20%">Student Section</th>
    <th width="20%">Cohort Section</th>
    <th width="20%">Cohort</th>
    <th width="10%">RS</th>
    <th width="30%">Student</th>
  </tr>
  <% students.each do |student| %>
    <tr>
      <td><%= student.section.name %></td>
      <td><%= student.cohort.section.nil? ? "" : student.cohort.section.name %></td>
      <td><%= student.cohort.name %></td>
      <td><%= student_status_string_short(student) %></td>
      <td><%= link_to_if(present_user.can_read?(student), student.full_name(present_user), student) %></td>
    </tr>
  <% end %>
  </table>

</div>

<%= section "Other Class Settings", {:classes => 'first no_bar' } do %>

  <%= form_for([@course, @klass]) do |f| %>

    <div class="field">
      Allow instructors to give assignments to specific cohorts?
      <%= f.radio_button :enable_assignment_by_cohort, true %> Yes
      <%= f.radio_button :enable_assignment_by_cohort, false %> No  
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% end %>

<%
  navitem(present_user.can_read?(@klass)) { link_to('Back to Class', klass_path(@klass)) }
  navitem(:can_read_children?, @klass, :sections) { link_to("Sections", klass_sections_path(@klass)) }
  navitem(:can_read_children?, @klass, :cohorts) { link_to("Cohorts", klass_cohorts_path(@klass)) }
%>

app/views/classes/show.html.erb
<%# Copyright 2011-2012 Rice University. Licensed under the Affero General Public 
    License version 3 or later.  See the COPYRIGHT file for details. %>

<% addTestMeta {{:page_type  => "show"}} %>
<% addTestMeta {{:major_name => @klass.course.organization.name}} %>
<% addTestMeta {{:minor_name => @klass.course.name}} %>

<%= pageHeading "Class: #{@klass.course.name}"%>

<% 
  is_teacher = @klass.is_teacher?(present_user)
  is_educator = @klass.is_educator?(present_user)
  student = @klass.student_for(present_user) 
  is_student = !student.nil?
  student_cohort = student.try(:cohort)
%>

<%= section "Class Information", {:classes => 'first no_bar class_information' } do %>

<div style="float:right; padding-right:30px">
    
  <% if is_student %>

    <% if student.active? %>
      <%= link_to "Drop this class!", 
                  drop_student_path(student), 
                  :class => "link_button",
                  :method => :put,
                  :confirm => "Are you sure you want to drop this class?\n\nThis can only be undone by an instructor!" %>
    <% end %>

  <% else %>

    <% rr = @klass.registration_requests.select{|rr| rr.user_id == present_user.id} %>

    <% if !rr.empty? %>
      <center>
        <%= button_to "Cancel my request to join this class", 
                       registration_request_path(rr),
                       :method => :delete,
                       :confirm => "Are you sure you want to cancel your registration request?",
                       :class => 'link_button' %>
      </center>
    <% elsif user_signed_in? %>
      <%= link_to "Register", 
                  new_klass_registration_request_path(@klass), 
                  :class => 'link_button', :remote => true %>
    <% end %>
    
  <% end %>  
</div>

  <% 
    educators = @klass.educators
    instructors = educators.select{|e| e.is_instructor} 
    tas = educators.select{|e| e.is_teaching_assistant}
    graders = educators.select{|e| e.is_grader}
  %>
  
  <% can_add_educator = present_user.can_create?(Educator.new(:klass => @klass)) %>
  
  <table class="left_heading">
    <tr>
      <th style="text-align:right">Course Name</th>
      <td><%= @klass.course.name %></td>
    </tr>
    <tr>
      <th style="text-align:right">Instructors</th>
      <td style="vertical-align:top">
        <span id="klass_instructor_list">
          <% if instructors.none? %>
            Pending
          <% else %>
            <% instructors.each do |instructor| %>
              <%= render :partial => 'classes/educator_entry', :locals => {:educator => instructor} %>
            <% end %>
          <% end %>
        </span>
        <% if can_add_educator %>
          <%= link_to "Add an instructor...", new_klass_educator_path(@klass, {:type => 'instructor'}), :remote => true %>
        <% end %>
      </td>
    </tr>
  
    <% if tas.any? || can_add_educator %>
    <tr>
      <th style="text-align:right">Teaching Assistants</th>
      <td style="vertical-align:top">
        <span id="klass_teaching_assistant_list">
          <% tas.each do |ta| %>
            <%= render :partial => 'classes/educator_entry', :locals => {:educator => ta} %>
          <% end %>
        </span>
        <% if can_add_educator %>
          <%= link_to "Add an assistant...", new_klass_educator_path(@klass, {:type => 'teaching_assistant'}), :remote => true %>
        <% end %>
      </td>
    </tr>
    <% end %>
    
    <% if graders.any? || can_add_educator %>
    <tr>
      <th style="text-align:right">Graders</th>
      <td style="vertical-align:top">
        <span id="klass_grader_list">
          <% graders.each do |grader| %>
            <%= render :partial => 'classes/educator_entry', :locals => {:educator => grader} %>
          <% end %>
        </span>
        <% if can_add_educator %>
          <%= link_to "Add a grader...", new_klass_educator_path(@klass, {:type => 'grader'}), :remote => true %>
        <% end %>
      </td>
    </tr>
    <% end %>

    <tr>
      <th style="text-align:right">Open Date</th>
      <td><%= standard_datetime(@klass.open_date) %></td>
    </tr>
    <tr>
      <th style="text-align:right">Start Date</th>
      <td><%= standard_datetime(@klass.start_date) %></td>
    </tr>
    <tr>
      <th style="text-align:right">End Date</th>
      <td><%= standard_datetime(@klass.end_date) %></td>
    </tr>
    <tr>
      <th style="text-align:right">Close Date</th>
      <td><%= standard_datetime(@klass.close_date) %></td>
    </tr>
    
    <% if @klass.is_teaching_assistant?(present_user) %>

    <tr>
      <th style="text-align:right">Preapprovals?</th>
      <td><%= tf_to_yn(!@klass.approved_emails.blank?) %></td>
    </tr>

    <tr>
      <th style="text-align:right">Consent Form</th>
      <td><%= @klass.consent_options.consent_form.try(:name) || "None selected" %></td>
    </tr>

    <tr>
      <th style="text-align:right">Is Embedded?</th>
      <td><%= tf_to_yn(@klass.is_embedded) %></td>
    </tr>

    
    <% end %>
    
    <% if is_student && @klass.is_controlled_experiment && student.currently_consentable? %>
    
    <tr>
      <th style="text-align:right">Consent</th>
      <td><%= link_to "View/Update", new_student_consent_path(student) %>
    </tr>
    
    <% end %>
    
    <% num_sections = @klass.sections.count %>
    <% @klass.sections.each_with_index do |section,ii| %>
    
      <tr class="test test_section">
        <th style="text-align:right"><%= "Enrollment" if ii == 0 %></th>
        <td>
          <%= link_to_if(present_user.can_read_children?(section, :students), 
                         "#{section.students.registered.active.count} Registered",
                         klass_students_path(@klass),
                         :test => "registered") %> |
          <%= link_to_if(present_user.can_read_children?(section, :students), 
                         "#{section.students.auditing.active.count} Auditing",
                         klass_students_path(@klass),
                         :test => "auditing") %>
          <% if @klass.is_teaching_assistant?(present_user) %>
            | <%= link_to("#{section.registration_requests.count} Pending", 
                          klass_registration_requests_path(@klass),
                          :test => "pending") %>
          <% end %>
          <%= "&nbsp;(#{section.name})".html_safe if num_sections > 1 %>
        </td>
      </tr>
    
    <% end %>
    
  </table>

<% end %>

<% sees_all_cohort_assignments = is_educator || present_user.is_researcher? || present_user.is_administrator? %>

<%= section "Registration Status", {:classes => "registration_status"} do %>
  <% if is_student %>
    <% if student.has_dropped? %>
      <p>You have dropped this class.</p>
    <% else %>
      <% if student.registered? %>
        <p>You are fully registered for this class.</p>
      <% elsif student.auditing? %>
        <p>You are auditing this class.</p>
      <% end %>
      <p>You are in section <%= student.section.name %>.</p>
    <% end %>
  <% else %>
    <p>You have not signed up for this class.</p>
  <% end %>
<% end %>

<% if !is_student || student.has_dropped? || !present_user.can_read_children?(@klass.cohorts.first, :assignments) %>
  <%= section "Assignments", {:classes => "assignments"} do %>
    <p>Assignments are only visible to this section's students and educators.</p>
  <% end %>
<% else %>
  <% if is_student %>
      <%= render :partial => 'student_assignments', :locals => { :student => student,
                                                                 :klass   => @klass, 
                                                                 :collapsible_section => sees_all_cohort_assignments} %>
  <% end %>
<% end %>

<% if sees_all_cohort_assignments %>
  <%= render :partial => 'nonstudent_assignments', :locals => {:present_user => present_user, :klass => @klass} %>
<% end %>

<%
  @force_nav_bar = true;
  navitem(present_user.can_update?(@klass)) { link_to('Edit Class', edit_klass_path(@klass)) }
  navitem(:can_read?, @klass.learning_plan) { link_to("Learning Plan", @klass.learning_plan) }
  navitem(:can_read_children?, @klass, :external_assignments) { link_to("External Assignments", klass_external_assignments_path(@klass)) }
  navitem(:can_read_children?, @klass, :management_overview) { link_to("Management Overview", management_overview_klass_path(@klass)) }
  navitem(:can_read_children?, @klass, :sections) { link_to("Sections", klass_sections_path(@klass)) }
  navitem(:can_read_children?, @klass, :learning_conditions) { link_to("Learning Conditions", klass_learning_conditions_path(@klass)) }
  navitem(:can_read_children?, @klass, :cohorts) { link_to("Cohorts", klass_cohorts_path(@klass)) }
  navitem(:can_read?, @klass.consent_options) { link_to("Consent Options", @klass.consent_options) }
  navitem(:can_read_children?, @klass, :report) { link_to("Report", report_klass_path(@klass, :format => :xls)) }
  navitem(:can_read_children?, @klass, :class_grades) { link_to("Class Grades", class_grades_klass_path(@klass, :format => :xls)) }
  navitem(:can_read_children?, @klass, :analytics) { link_to("Analytics", klass_analytics_path(@klass)) }
%>